### ISSUE TITLE
Why custom solution

### ISSUE THREAD

**Issue by MarekVigas** [bratislava/nest-health-worker#2]
Why would you create custom monitoring tool ? There are many free / open-source / self-hostable tools like [uptime-kuma](https://github.com/louislam/uptime-kuma)

**Comment by skifahrer** [comment]
Hi, Thanks for your notice @MarekVigas. 
From an outer perspective, having other open-source solutions for monitoring makes sense. 
But in our case, we just reused the older solution we already had on a different repository and put it here on github. We currently have an ongoing process of moving/merging all city repositories into one place. 
Also, I have to mention this solution was already integrated into our monitoring dashboards. As it doesn't look like it, it was easier/faster to do it this way as setting up some new monitoring infrastructure.

**Comment by mpinter** [comment]
Hey @MarekVigas - just a quick update, as we've been moving forward with our monitoring internally over the past months, we've also ended up with replacing this healthchecker with Uptime kuma at some point. The status page can be found here - https://status.bratislava.sk/

Thanks for the suggestion 🙂
